# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio_NyBank(object):
    def setupUi(self, Inicio_NyBank):
        Inicio_NyBank.setObjectName("Inicio_NyBank")
        Inicio_NyBank.resize(642, 480)
        Inicio_NyBank.setStyleSheet("background-color: rgb(196, 215, 255);")
        self.label = QtWidgets.QLabel(Inicio_NyBank)
        self.label.setGeometry(QtCore.QRect(60, 50, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Inicio_NyBank)
        self.label_2.setGeometry(QtCore.QRect(150, 110, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ButtonLogin = QtWidgets.QPushButton(Inicio_NyBank)
        self.ButtonLogin.setGeometry(QtCore.QRect(270, 250, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.ButtonLogin.setFont(font)
        self.ButtonLogin.setStyleSheet("color: rgb(0, 122, 0);\n"
"background-color: rgb(171, 200, 206,0);")
        self.ButtonLogin.setObjectName("ButtonLogin")
        self.ButtonCadastrar = QtWidgets.QPushButton(Inicio_NyBank)
        self.ButtonCadastrar.setGeometry(QtCore.QRect(270, 290, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ButtonCadastrar.setFont(font)
        self.ButtonCadastrar.setStyleSheet("color: rgb(0, 122, 0);\n"
"background-color: rgb(171, 200, 206,0);")
        self.ButtonCadastrar.setObjectName("ButtonCadastrar")
        self.ButtonSair = QtWidgets.QPushButton(Inicio_NyBank)
        self.ButtonSair.setGeometry(QtCore.QRect(500, 380, 80, 23))
        self.ButtonSair.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0,0);")
        self.ButtonSair.setObjectName("ButtonSair")
        self.lineUsuario = QtWidgets.QLineEdit(Inicio_NyBank)
        self.lineUsuario.setGeometry(QtCore.QRect(220, 170, 201, 21))
        self.lineUsuario.setStyleSheet("color: rgb(171, 171, 171);")
        self.lineUsuario.setText("")
        self.lineUsuario.setObjectName("lineUsuario")
        self.lineSenha = QtWidgets.QLineEdit(Inicio_NyBank)
        self.lineSenha.setGeometry(QtCore.QRect(220, 210, 201, 21))
        self.lineSenha.setStyleSheet("color: rgb(171, 171, 171);")
        self.lineSenha.setText("")
        self.lineSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineSenha.setObjectName("lineSenha")
        self.label_3 = QtWidgets.QLabel(Inicio_NyBank)
        self.label_3.setGeometry(QtCore.QRect(40, 420, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Inicio_NyBank)
        self.label_4.setGeometry(QtCore.QRect(150, 170, 57, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Inicio_NyBank)
        self.label_5.setGeometry(QtCore.QRect(150, 210, 57, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.labelNotificacao = QtWidgets.QLabel(Inicio_NyBank)
        self.labelNotificacao.setGeometry(QtCore.QRect(200, 350, 221, 20))
        self.labelNotificacao.setObjectName("labelNotificacao")

        self.retranslateUi(Inicio_NyBank)
        QtCore.QMetaObject.connectSlotsByName(Inicio_NyBank)

    def retranslateUi(self, Inicio_NyBank):
        _translate = QtCore.QCoreApplication.translate
        Inicio_NyBank.setWindowTitle(_translate("Inicio_NyBank", "Form"))
        self.label.setText(_translate("Inicio_NyBank", "Seja Bem-Vindo ao NyBank"))
        self.label_2.setText(_translate("Inicio_NyBank", "Está com você nos melhores e piores momentos =)"))
        self.ButtonLogin.setText(_translate("Inicio_NyBank", "Login"))
        self.ButtonCadastrar.setText(_translate("Inicio_NyBank", "Cadastrar-se"))
        self.ButtonSair.setText(_translate("Inicio_NyBank", "Sair"))
        self.label_3.setText(_translate("Inicio_NyBank", "NyBank"))
        self.label_4.setText(_translate("Inicio_NyBank", "Usuário:"))
        self.label_5.setText(_translate("Inicio_NyBank", "Senha:"))
        self.labelNotificacao.setText(_translate("Inicio_NyBank", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
